version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "8082:80"
    networks:
      - lab-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: lab_password
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge

