version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80" # Убедись, что этот порт настроен для dev окружения
    networks:
      - dev-network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example_password
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

