version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - app-network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example_password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

